[package]
authors      = ["Chat-rs Team"]
autoexamples = false
description  = "Build LLM clients with ease, attach them to your tools"
edition      = "2024"
license      = "MIT"
name         = "chat-rs"
version      = "0.0.1"

[lib]
name = "chat_rs"
path = "src/lib.rs"

[workspace]
resolver = "2"

[workspace.package]
authors      = ["Chat-rs Team"]
edition      = "2024"
license      = "MIT"
repository   = "https://github.com/EggerMarc/chat-rs"
rust-version = "1.91"

[workspace.dependencies]
chrono              = "0.4.41"
inventory           = "0.3.20"
async-trait         = "0.1.89"
reqwest             = "0.12.24"
serde               = { version = "1.0.228", features = ["derive"] }
serde_json          = "1.0.145"
thiserror           = "2.0.17"
tools-rs            = "0.1.5"
tools_core          = "0.1.4"
tools_macros        = "0.1.1"
tokio               = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time", "sync"] }

[dependencies]
async-trait.workspace   = true
inventory.workspace     = true
reqwest.workspace       = true
schemars = "1.1.0"
serde.workspace         = true
serde_json.workspace    = true
thiserror.workspace     = true
tokio.workspace         = true
tools-rs.workspace      = true
tools_core.workspace    = true
tools_macros.workspace  = true
url = { version = "2.5.8", features = ["serde"] }

[[example]]
name = "gemini-structured"
path = "./examples/gemini/structured.rs"

[[example]]
name = "gemini-code-execution"
path = "./examples/gemini/code_execution.rs"

[[example]]
name = "gemini-google-maps"
path = "./examples/gemini/google_maps.rs"

[[example]]
name = "gemini-tools"
path = "./examples/gemini/tools.rs"

[[example]]
name = "gemini-files"
path = "./examples/gemini/files.rs"
