[workspace]
resolver = "2"
members = [
    "core",
    "providers/gemini"
]

[workspace.package]
authors      = ["Chat-rs Team"]
edition      = "2024"
license      = "MIT"
repository   = "https://github.com/EggerMarc/chat-rs"
rust-version = "1.94" 

[workspace.dependencies]
async-stream        = "0.3.6"
async-trait         = "0.1.89"
chrono              = "0.4.41"
futures             = "0.3.32"
infer               = "0.19.0"
inventory           = "0.3.20"
reqwest             = "0.12.24"
schemars            = "1.1.0"
serde               = { version = "1.0.228", features = ["derive"] }
serde_json          = "1.0.145"
thiserror           = "2.0.17"
tokio               = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
tools-rs            = "0.1.5"
tools_core          = "0.1.4"
tools_macros        = "0.1.1"
url                 = { version = "2.5.8", features = ["serde"] }

[package]
name         = "chat-rs"
version      = "0.0.6"
description  = "Build LLM clients with ease, attach them to your tools"
autoexamples = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "chat_rs"
path = "src/lib.rs"

[dependencies]
chat-core   = { path = "core" }
chat-gemini = { path = "providers/gemini", optional = true }

[dev-dependencies]
regex     = "1"
once_cell = "1"
tokio     = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = []
gemini = ["dep:chat-gemini"]
stream = ["chat-core/stream", "chat-gemini?/stream"]


[[example]]
name = "gemini-structured"
path = "./examples/gemini/structured.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-code-execution"
path = "./examples/gemini/code_execution.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-google-maps"
path = "./examples/gemini/google_maps.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-tools"
path = "./examples/gemini/tools.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-youtube"
path = "./examples/gemini/youtube.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-embeddings"
path = "./examples/gemini/embeddings.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-classification"
path = "./examples/gemini/classification.rs"
required-features = ["gemini"]

[[example]]
name = "gemini-image-understanding"
path = "./examples/gemini/image_understanding.rs"
required-features = ["gemini"]

[[example]]
name = "retry"
path = "./examples/retry.rs"
required-features = ["gemini"]

