[package]
name = "chat-huggingface"
version = "0.2.6"
description = "Hugging Face Inference Providers (Router) for chat-rs."
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[dependencies]
chat-completions = { path = "../completions", version = "0.3.1" }

[dev-dependencies]
chat-core = { path = "../../core", version = "0.4.2", features = ["reqwest-transport"] }
tokio.workspace = true

[features]
default = []
stream = ["chat-completions/stream"]
