[package]
name = "chat-openai"
version = "0.0.4"
description = "Provider implementation of OpenAI for chat-rs"
edition.workspace = true
authors.workspace = true
license.workspace = true


[dependencies]
chat-core = { path = "../../core", version = "0.0.6" }

async-trait.workspace = true
reqwest = { workspace = true, features = ["json", "stream"] }
serde.workspace = true
serde_json.workspace = true
tools-rs.workspace = true
async-stream = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
schemars.workspace = true
base64              = "0.22.1"

[features]
default = []
stream = ["chat-core/stream", "dep:async-stream", "dep:futures"]
