[package]
name = "chat-gemini"
version = "0.2.5"
description = "Provider implementation of Gemini for chat-rs"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
chat-core = { path = "../../core", version = "0.4.0", features = ["reqwest-transport"] }

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tools-rs.workspace = true
futures = { workspace = true, optional = true }
async-stream = { workspace = true, optional = true }
schemars.workspace = true
base64              = "0.22.1"
tracing             = "0.1"

[dev-dependencies]
chat-core = { path = "../../core", version = "0.4.0", features = ["reqwest-transport", "testing"] }
tokio.workspace = true
serde_json.workspace = true

[features]
default = []
stream = ["chat-core/stream", "dep:async-stream", "dep:futures"]
