[package]
name = "chat-gemini"
version = "0.0.2"
description = "Provider implementation of Gemini for chat-rs"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chat-core = { path = "../../core", version = "0.0.2"}

async-trait.workspace = true
reqwest = { workspace = true, features = ["json"] } 
serde.workspace = true
serde_json.workspace = true
tools-rs.workspace = true
schemars.workspace = true
base64              = "0.22.1"

[features]
default = []
stream = ["chat-core/stream"]
