[package]
name = "chat-claude"
version = "0.2.2"
description = "Provider implementation of Claude for chat-rs"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chat-core = { path = "../../core", version = "0.2.2", features = ["reqwest-transport"] }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tools-rs.workspace = true
schemars.workspace = true
futures = { workspace = true, optional = true }
async-stream = { workspace = true, optional = true }
base64 = "0.22.1"

[dev-dependencies]
chat-core = { path = "../../core", version = "0.2.2", features = ["reqwest-transport", "testing"] }
tokio.workspace = true
serde_json.workspace = true

[features]
default = []
stream = ["chat-core/stream", "dep:async-stream", "dep:futures"]
