[package]
name = "chat-router"
version = "0.0.1"
description = "Router for multiple clients"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chat-core = { path = "../../core", version = "0.0.4" }
async-trait.workspace = true
schemars.workspace = true
tools-rs.workspace = true
